services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: always
    networks:
      - searxng
    ports:
      - "8085:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8085/
      - SEARXNG_SECRET=${SEARXNG_SECRET_KEY:-ultrasecretkey1234501}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --save "" --appendonly no --maxmemory 30mb --maxmemory-policy allkeys-lru
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    ipam:
      driver: default
