# SearXNG settings

use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "ultrasecretkey" # Should be updated via .env in production
  limiter: false # Disable rate limiter for local dev
  image_proxy: true

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
  - name: bing
    engine: bing
    shortcut: b
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

ui:
  static_path: ""
  templates_path: ""
  theme: simple
